### ISSUE TITLE
Relacionado al issue #10 - Crear clase Fallecidos

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#12]
Depende del Issue #10 ya que hereda de dicha clase
La especificacion esta en el issue #6

Prestar atencion a como se resolvio, En el issue #10, el tema de los campos:

    borrado
    motivo_borrado
    fecha_borrado
    usuario_borrador
    historico
    fecha_historico
    marca_creacion
    usuario_creador
    marca_ultima_modificacion
    motivo_modificacion
    usuario_ultima_modificacion

**Comment by lokiyin** [comment]
ok

**Comment by rafaelferrero** [comment]
@lokiyin ya podes intenar crear esta clase... sino me avisas y nos juntamos
