### ISSUE TITLE
Revisar modulo Tipos de Documento

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#28]
¿Será tan necesario tener ese modulo... o lo pasamos a un choices.py dentro del modulo personas?

**Comment by Gnoq** [comment]
Me parece que a largo plazo, debería estar el módulo, siempre pensando en que el sistema se va a expandir... Hoy para el cuartel, creería que solo tenemos D.N.I., es raro encontrar otro tipo de documento... Igual, opino mantenerlo como módulo aparte, como está ahora.

**Comment by rafaelferrero** [comment]
Igual creo que se puede, tranquilamente cargar el nuevo tipo de documento de en el archivo choices.py y a la puta... y reducimos un poco de complejidad al projecto.

**Comment by rafaelferrero** [comment]
Y se fué nomás. Lo hice choices.
