### ISSUE TITLE
Ficha Médica

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#39]
Crear los modelos necesarios para gestionar la Ficha Médica de cada Bombero (similar al sistema anterior por ahora)

**Comment by lokiyin** [comment]
hola para no gastar energías y avansar mas rapido porque por el momento no guardamos el dato donde esta guardada la ficha medica unicamente.. para luego cuando el sistema ya este en funcionamiento ir puliendo detalles y terminando el asusnto .. por ejemplo...  que ficha medica contenga el numero de cajón y el indice donde esta la carpeta con ultima ficha medica de x bombero.  es una propuesta para agilizar.

**Comment by rafaelferrero** [comment]
Si, claro.
En el legajo se muestra información básica.. las alergias de cada bombero
pueda tener, qué mutual tiene, qué plan, etc.
Si pensamos a futuro, esta parte del legajo en realidad debería ser un
módulo aparte que se llame algo como "ficha_medica" o "historial_medico"...
no sé algo... Este módulo debería serle útil a la gente de el área de
salud... con todo lo que ellos necesiten.
Una parte de lo que hace salud va al legajo, y como afecta al Milestone
actual... lo hacemos, luego en su momento vemos con más detenimiento y
profundidad eso.

Agregar sólo ese dato no es enquilombado, lo podemos hacer. Me parece a mí.


Rafael E. Ferrero
