### ISSUE TITLE
Crear Gestion de Actas

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#40]
Crear los modelos necesarios para gestionar las Actas. 
Se pide que de acuerdo a cada acta el sistema interprete cuándo es un Ascenso, o Premio, o Sanción, o Vacaciones, etc. Cada uno de estos luego será impreso en el legajo personal del Bombero involucrado.
En base al último ascenso se tomará el grado del Bombero a mostrar en el legajo impreso.
En base al Acta de Ascenso del tipo Alta se tomaran los datos para el legajo impreso.

**Comment by lokiyin** [comment]
la clase actas esta lista .. faltaria que me des las condiciones para las sub clases de el propocito del acta ....... asenso, sancion , vacaciones.. etc .... cuales son y que campos necesita cada una.
