### ISSUE TITLE
Calificación Anual

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#42]
Indicar la calificación anual obtenida por el bombero.
Indicar:
- Periodo de la calificacion (Año)
- Puntaje en numero (Decimal)
- Calificacion en letras (Muy Bueno | Bueno | Regular, etc) (Sería un Choice)*

La calificación en letras... ¿No está atado al puntaje en valor decimal? Esto podría ser calculado y no ingresado a mano

**Comment by rafaelferrero** [comment]
Cristian indica:

> APRECIACIÓN GENERAL DE LA CALIFICACIÓN Y SU CORRESPONDIENTE CONCEPTO:
> El que obtuviere de:
> a. 19 a 20 Puntos excelente
> b. 16 a 18 muy bueno
> c. 10 a 15 bueno
> d. 0 a 9 Insuficiente

**Comment by lokiyin** [comment]
jje yo pondria ...

a. 19 a 20 Imposible.
b. 16 a 18 Búscate una familia o dale bola a la que tenes.
c. 10 a 15 Gracias por ser bombero.
d. 0 a 9 Si seguís jodiendo te corro.

**Comment by Gnoq** [comment]
Listo, me pongo con ésto entonces!

2017-01-18 9:38 GMT-03:00 Rafael E. Ferrero <notifications@github.com>:

**Comment by Gnoq** [comment]
Pregunta: Hay que ingresar además del puntaje numérico decimal, si es insoficiente, bueno, muy bueno o excelente o el programa lo tiene que calcular solo?

**Comment by Gnoq** [comment]
Ya con algo de trabajo hecho, me parece que, de acuerdo al puntaje numérico, el sistema debe identificar el puntaje escrito.

Para hacer ésto, me surgieron dos problemas,
1-¿cómo hago limitar el DecimalField de puntaje numérico para que vaya de 0 a 20?
2-¿cómo hago que, depende al número, identifique el puntaje escrito?

Voy a estudiar y repasar el curso de la facultad para ver si lo explica, si hay algún tutorial que les haya servido se agradece.

**Comment by rafaelferrero** [comment]
Yo dejaría el puntaje escrito para mas adelante... porque, si bien nosotros
no sé si en algún momento cambiaremos la escala, pero habría tal vez que
prever que se cambie la escala en algún periodo de tiempo.
Yo diría que por el momento ese campo sea un DecimalField sin
restricciones... y/o pensa como podrias almacenar las escalas.

Respecto de las restricciones... creo que sobreescribiendo el método clean
podes programar la restricción.

**Comment by rafaelferrero** [comment]
https://docs.djangoproject.com/en/1.10/ref/models/instances/#validating-objects

**Comment by Gnoq** [comment]
Solucioné el problema de la restricción sobrescribiendo el método clean, como me indicaste Rafa, muchas gracias!
En tanto al puntaje escrito, ¿sería conveniente dejar el campo en la clase o lo agregamos después con sus requerimientos?

Saludos!

**Comment by rafaelferrero** [comment]
El puntaje escritor por ahora no lo hagamos, porque interpreto que eso
también puede cambiar en el tiempo.


Rafael E. Ferrero

**Comment by Gnoq** [comment]
Para dejar un registro, voy a agregar un método que me devuelva en palabra la calificación (Insuficiente, buena, muy buena o excelente), que será llamada en el __str__.
Saludos!

**Comment by rafaelferrero** [comment]
Genial!, igual no hace falta que dejes registro de ello acá... lo vemos en
los commit directamente. ;)
