### ISSUE TITLE
Alergias

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#49]
Relacionado con #39 
Posibilidad de indicar las alergias que pudiera tener un bombero.
Tener en cuenta que un Bombero puede tener muchas alergias.

**Comment by lokiyin** [comment]
no entiendo a que te referis rafa

**Comment by rafaelferrero** [comment]
Es facil culiado.... una persona puede ser alergico a muchas cosas


Rafael E. Ferrero

2016-11-10 22:47 GMT-03:00 lokiyin <notifications@github.com>:

**Comment by fmoreyra** [comment]
Pregunta: Cómo puedo limitar a una sola la relación entre alérgeno y alérgicos?

**Comment by rafaelferrero** [comment]
¿Sería para que no se pueda elegir dos veces el mismo alérgeno a un mismo bombero? con un unique_together mirá acá [https://docs.djangoproject.com/en/1.10/ref/models/options/#unique-together](url)

**Comment by fmoreyra** [comment]
Si, justamente, para evitar repeticiones. Muchas gracias!! anda perfecto
