### ISSUE TITLE
Cobertura Médica

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#51]
Relacionado con #39 

Indicar Obra Social / Prepaga y su correspondiente plan
Médico de cabecera
Clínica donde se atiende

Tanto el Médico de Cabecera como la Clínica donde se atienden debería  ser cargado como Persona e Institución respectivamente, con lo cual podría cargarse los medios de contacto de cada uno.

**Comment by fmoreyra** [comment]
Hola rafa! estuve viendo la issue, tengo un par de dudas:

1_ En cuanto al número de afiliado a la obra social del bombero, dicho campo lo puse en cobertura médica, ya que sería, según el diagrama, la única forma de relacionar la obra social (por medio del plan) y el bombero. Se podría hacer dicha relación (obra social y bombero) dentro del plan médico? me parece que tendría más sentido en ese caso.

2_ Respecto del plan médico, qué datos serían útiles para incluir en el sistema? Puse un textField a modo de descripción, no sé si apunta a agregar algo más...

Eso por ahora. Ya avanzé con el código hasta completar lo que se pedía en la issue, pero me quedaron dichas dudas

**Comment by rafaelferrero** [comment]
Hola Facu !!
Esto fué lo que yo razoné:
Un Bombero, a lo largo de su vida, puede haber pasado por muchas Obras
Sociales (muchas veces dependiendo de las empresas en las que trabajó, te
dan OSDE, CAMI, o la del gremio... que se yo) por eso esta planteado que un
bombero puede tener muchas coberturas médicas.
Cada cobertura médica esta relacionada a una obra social mediante un plan.
Es decir, cada Obra Social puede tener muchos planes (y un plan una obra
social)
Dependiendo de qué obra social y plan tenga el bombero va a poder ser
atendido en unas clínicas y en otras no... idem para los medicos. Con lo
cual la clínica donde prefiera atenderse dependerá si la mutual se la cubre
y su medico de cabecera también.

¿Se entiende?

**Comment by fmoreyra** [comment]
Si, había entendido más o menos eso, mi duda más vale era si el número de afiliado (Campo que agregué yo, no sé si se pone en realidad, rellené las clases con campos según iba considerando necesario) no depende del plan que se tenga... si no se podría poner en el plan, como puse arriba. Esto que te menciono es lo único que me hace ruido, porque, si se cumple que es siempre el mismo número, si el bombero cambia de plan médico (quedándose en la misma obra social) se repetiría el nro de afiliado.
Habría algún problema con hacerte pull request así ves lo que fui haciendo? si no se modifica lo que te digo estaría listo...

**Comment by rafaelferrero** [comment]
Facu, entre a ver tu codigo. A mí entender el número de afiliado va en la
Cobertura, si cambia de plan en la misma ObraSocial, podes o bien cambiarle
el plan y sigue con el mismo numero de afiliado... o bien le creas otra
cobertura (las coberturas deberan tener un periodo de tiempo)

**Comment by fmoreyra** [comment]
Entonces faltaría un campo de tiempo? (desde-hasta)?

**Comment by rafaelferrero** [comment]
Claro, porque como te dije, uno podría haber pasado por muchas mutuales a
lo largo de su vida (Yo tuve OSECAC, la de SMATA, Swiss Medical, OSPE y
ahora CAMI)

Se entiende ?

**Comment by fmoreyra** [comment]
Sisi, me sirve porque me parecía que faltaba algún que otro campo! Si tenés algo para decir de las demás clases, lo modifico, no hay drama. Ya lo agrego!

**Comment by rafaelferrero** [comment]
Vamos viendo, en principio lo hacemos asi despues le vamos metiendo más
musculo a este esqueleto jeje.
