### ISSUE TITLE
Fecha de Vencimiento de la Credencial de Bomberos

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#52]
Agregar la Fecha de Vencimiento de la Credencial de Bomberos a la clase Bomberos
Relacionado con #6

**Comment by lokiyin** [comment]
If dateVence = to date ;

Print " bombero precenta credencial vencida"

**Comment by rafaelferrero** [comment]
preSenta

**Comment by rafaelferrero** [comment]
Mati, agrega este campo a la clase Bombero. Este campo debe permitir blancos y nulos porque no siempre un bombero tiene credencial

**Comment by lokiyin** [comment]
qsl

**Comment by lokiyin** [comment]
TRABAJO TERMINADO.
