### ISSUE TITLE
Aplicación para la Gestión de Grados

### ISSUE THREAD

**Issue by fmoreyra** [bvsf/sigcaw#61]
Crear aplicación para la creación, modificación o eliminación de grados, teniendo en cuenta los requisitos para estar en dicho cargo.

**Comment by Gnoq** [comment]
Dejo un ayuda memoria sobre esta app

Grados: Nombre específico el grado (los que pasé arriba)
Escalafón: Colección de grados (títulos de los grupos de grados de arriba)
Rango: Oficial, Sub Oficial, Bombero.

**Comment by lokiyin** [comment]
ya esta listo esto emi? o necesitas algo en particular?

**Comment by Gnoq** [comment]
> ya esta listo esto emi? o necesitas algo en particular?
 Listo Mati, había problema en un procedimiento!
Gracias igual.
