### ISSUE TITLE
Crear tabla para Cuarteleros

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#76]
Los Cuarteleros son una clase especial de usuarios. Pueden o NO ser bomberos y sí o sí son Personas.
Hay que representarlos en la base de datos porque tienen permisos especiales.

**Comment by Gnoq** [comment]
Sería mucho más fácil que despidan a los cuarteleros que son Bomberos, ¿no?
Cristian, nos complicas las cosas! Jajaja
