### ISSUE TITLE
ACTAS - Baja de Bombero

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/sigcaw#96]
El procedimiento de baja es el siguiente.
El Bombero envía un Pase Interno (una carta interna) a Jefatura solicitando su baja a partir de una determinada fecha.
Jefatura aprueba en primer instancia la baja, y se presenta el Pase Interno en Comisión Directiva. 
Comisión Directiva acepta el Pase Interno y asienta la misma en un Acta.
La fecha de la baja es la indicada en el Pase Interno.

Crear el Acta para registrar las Bajas de los Bomberos.

Debe Heredar de la clase [Actas](https://github.com/bvsf/sigcaw/blob/ffaf6732ef4b1583e92376d1a5a49e79250ac21b/actas/models.py#L43) indicar:
- **bombero** como Foreignkey a la clase [Bombero](https://github.com/bvsf/sigcaw/blob/ffaf6732ef4b1583e92376d1a5a49e79250ac21b/personas/models.py#L141)
- **fecha_solicitud** como campo del tipo Fecha indicando la fecha en que se realizó el Pase Interno
- **fecha_efectiva** como campo del tipo Fecha indicando cuándo efectivamente el Bombero deja de formar parte del Cuerpo Activo.

Al Guardar un **nuevo registro** de la clase baja se debe cerrar la vigencia del numero de orden de dicho bombero a la fecha especificada en el campo **fecha_efectiva**

**Comment by Gnoq** [comment]
¿Dar de alta un Bombero cómo se registra?

**Comment by rafaelferrero** [comment]
Tendríamos que definir bien el circuito, desde que se retiran las planillas
hasta que se confirme el alta.
¿Tal vez podamos hacer la inscripción Online?... hay que definirlo con
Cristian Carle.
